alpha=1;
for i=1:3
    for j=100:10:100000
        for k=1:3
            for l=1:10
                if(exist(['Matriz' num2str(i) '_Incendios' num2str(j) ...
                        '_Teste' num2str(k) '_Estado' num2str(l) ...
                        '.txt'], 'file')~=0)
                   data(alpha).matriz = importdata(['Matriz' num2str(i) ...
                        '_Incendios' num2str(j) '_Teste' num2str(k) ...
                        '_Estado' num2str(l) '.txt']);
                    h = figure;
                    mymap = [0 1 0; 0 0 1; 1 0 0; 0 0 0; 1 1 0];
                    imshow(1.+data(alpha).matriz, ...
                        colormap (mymap));
                    %savefig (['Figura' num2str(alpha) ...
                    %    '_Matriz' num2str(i) ...
                    %    '_Incendios' num2str(j) ...
                    %    '_Teste' num2str(k) ...
                    %    '_Estado' num2str(l) '.fig']);
                    saveas (h, ['Figura' num2str(alpha) ...
                        '_Matriz' num2str(i) ...
                        '_Incendios' num2str(j) ...
                        '_Teste' num2str(k) ...
                        '_Estado' num2str(l) '.jpg']);
                    alpha=alpha+1;
                end
                if (exist(['Matriz' num2str(i) '_Incendios' num2str(j) ...
                    '_Teste' num2str(k) '_Estado' num2str(l) ...
                        '_Vento.txt'], 'file')~=0)
                    data(alpha).matriz = importdata(['Matriz' num2str(i) ...
                        '_Incendios' num2str(j) '_Teste' num2str(k) ...
                        '_Estado' num2str(l) '_Vento.txt']);
                    h = figure;
                    mymap = [1 1 1; 0.2 0 0];
                    imshow(1.+data(alpha).matriz, ...
                        colormap (mymap));
                    saveas (h, ['Figura' num2str(alpha) ...
                        '_Matriz' num2str(i) ...
                        '_Incendios' num2str(j) ...
                        '_Teste' num2str(k) ...
                        '_Estado' num2str(l) '_Vento.jpg']);
                    alpha=alpha+1;
                end
                if (exist(['Matriz' num2str(i) '_Incendios' num2str(j) ...
                    '_Teste' num2str(k) '_Estado' num2str(l) ...
                    '_Chuva.txt'], 'file')~=0)
                    data(alpha).matriz = importdata(['Matriz' num2str(i) ...
                        '_Incendios' num2str(j) '_Teste' num2str(k) ...
                        '_Estado' num2str(l) '_Chuva.txt']);
                    h = figure;
                    mymap = [1 1 1; 0 0 1];
                    imshow(1.+data(alpha).matriz, ...
                        colormap (mymap));
                    saveas (h, ['Figura' num2str(alpha) ...
                        '_Matriz' num2str(i) ...
                        '_Incendios' num2str(j) ...
                        '_Teste' num2str(k) ...
                        '_Estado' num2str(l) '_Chuva.jpg']);
                    alpha=alpha+1;
                end
            end
        end
    end
end

